name: Release to github packages

on:
  release:
    types: [ created ]

jobs:
  call-workflow-release:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-release.yml@main
    with:
      java-version: 11
    secrets:
      packages-user: ${{ secrets.CREATE_PACKAGES_USER }}
      packages-token: ${{ secrets.CREATE_PACKAGES_TOKEN }}
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
      
